variable "vpc_cidr" {}
variable "public1_az" {}
variable "public1_cidr" {}
variable "public2_az" {}
variable "public2_cidr" {}
variable "private1_az" {}
variable "private1_cidr" {}
variable "private2_az" {}
variable "private2_cidr" {}
variable "domain_name" {}
variable "route_cidr" {}
